// Auto-generated. Do not edit.


    declare const enum protocolCommand {
    COMMAND_REQUEST = 0x20,
    COMMAND_REQUEST_BLOCKS = 33,
    COMMAND_REQUEST_ARROWS = 34,
    COMMAND_REQUEST_LEARNED = 35,
    COMMAND_REQUEST_BLOCKS_LEARNED = 36,
    COMMAND_REQUEST_ARROWS_LEARNED = 37,
    COMMAND_REQUEST_BY_ID = 38,
    COMMAND_REQUEST_BLOCKS_BY_ID = 39,
    COMMAND_REQUEST_ARROWS_BY_ID = 40,

    COMMAND_RETURN_INFO = 41,
    COMMAND_RETURN_BLOCK = 42,
    COMMAND_RETURN_ARROW = 43,

    COMMAND_REQUEST_KNOCK = 44,
    COMMAND_REQUEST_ALGORITHM = 45,

    COMMAND_RETURN_OK = 46,
    }


    declare const enum protocolAlgorithm {
    ALGORITHM_FACE_RECOGNITION = 0,
    ALGORITHM_OBJECT_TRACKING = 1,
    ALGORITHM_OBJECT_RECOGNITION = 2,
    ALGORITHM_LINE_TRACKING = 3,
    ALGORITHM_COLOR_RECOGNITION = 4,
    ALGORITHM_TAG_RECOGNITION = 5,
    ALGORITHM_OBJECT_CLASSIFICATION = 6,
    }

// Auto-generated. Do not edit. Really.
